export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const ADD_SPACE_REQUEST = 'ADD_SPACE_REQUEST';
export const ADD_SPACE_SUCCESS = 'ADD_SPACE_SUCCESS';
export const ADD_SPACE_FAILURE = 'ADD_SPACE_FAILURE';

