export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const ADD_PLACE_REQUEST = 'ADD_PLACE_REQUEST';
export const ADD_PLACE_SUCCESS = 'ADD_PLACE_SUCCESS';
export const ADD_PLACE_FAILURE = 'ADD_PLACE_FAILURE';

export const ADD_MANAGER_REQUEST = 'ADD_MANAGER_REQUEST';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';
export const ADD_MANAGER_FAILURE = 'ADD_MANAGER_FAILURE';

